version: '3'
services:
  mysql:
    container_name: database_teste_itau
    image: mysql:5.7.10
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: teste_itau
      MYSQL_PASSWORD: teste_itau
      MYSQL_DATABASE: teste_itau
    ports:
      - 3306:3306
    volumes:
      - .Itau.Teste.DataBase/data:/var/lib/mysql
        
  api:
    build:
      dockerfile: ./Itau.Teste.API/Itau.Teste.API/Dockerfile
      context: .
    container_name: api_teste_itau
    ports:
      - 8081:80
    depends_on:
      - mysql
    
  front:
    build:
      dockerfile: ./Itau.Teste.Front/Dockerfile
      context: .
    container_name: front_teste_itau
    ports:
      - 8082:80
    depends_on:
      - api

volumes:
  data: