// <auto-generated />
using System;
using Itau.Teste.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Itau.Teste.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210310021608_SeedAjustesFinanceiro")]
    partial class SeedAjustesFinanceiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Itau.Teste.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<bool>("Conciliado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("CONCILIADO");

                    b.Property<DateTime>("DataHoraLancamento")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_HORA_LANCAMENTO");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id")
                        .HasName("ID");

                    b.ToTable("teste_itau.LANCAMENTOS_FINANCEIROS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 1, 12, 4, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 3000m
                        },
                        new
                        {
                            Id = 2,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 1, 13, 3, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 1,
                            Valor = 100m
                        },
                        new
                        {
                            Id = 3,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 1, 14, 2, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 1,
                            Valor = 55m
                        },
                        new
                        {
                            Id = 4,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 2, 14, 3, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 72m
                        },
                        new
                        {
                            Id = 5,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 2, 14, 47, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 1,
                            Valor = 153m
                        },
                        new
                        {
                            Id = 6,
                            Conciliado = true,
                            DataHoraLancamento = new DateTime(2021, 3, 3, 15, 43, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 1,
                            Valor = 342m
                        },
                        new
                        {
                            Id = 7,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 3, 15, 32, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 1,
                            Valor = 75m
                        },
                        new
                        {
                            Id = 8,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 3, 16, 57, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 1,
                            Valor = 145m
                        },
                        new
                        {
                            Id = 9,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 3, 17, 34, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 234m
                        },
                        new
                        {
                            Id = 10,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 3, 4, 17, 41, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 876m
                        },
                        new
                        {
                            Id = 11,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 4, 4, 18, 35, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 234m
                        },
                        new
                        {
                            Id = 12,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 4, 4, 11, 24, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 56m
                        },
                        new
                        {
                            Id = 13,
                            Conciliado = false,
                            DataHoraLancamento = new DateTime(2021, 4, 4, 11, 21, 0, 0, DateTimeKind.Unspecified),
                            Tipo = 2,
                            Valor = 213m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
